// react/my-app/src/TodoListItem.js
import React from 'react';

/**
 * Renders a single todo item into a card
 * @param {{todoItem: import('./api/todotype').TodoItem}} props
 */
const TodoListItem = ({ todoItem }) => {
  return (
    <div className="card">
      <div className="container">
        <h4>{todoItem.title} </h4>
        <span style={{ fontStyle: 'italic' }}>{todoItem.description} </span>
        <div>Luotu: {todoItem.createdAt.toLocaleString()}</div>
        <div>{todoItem.done ? 'Tehty' : 'Kesken'}</div>
      </div>
    </div>
  );
};

export default TodoListItem;

// angular/my-app/src/app/todo-list-item/todo-list-item.component.ts
import { Component, OnInit, Input } from "@angular/core";
import { TodoItem } from "../services/todo-service.service";

@Component({
  selector: "app-todo-list-item",
  templateUrl: "./todo-list-item.component.html",
  styleUrls: ["./todo-list-item.component.css"]
})
export class TodoListItemComponent implements OnInit {
  constructor() {}

  @Input() todoItem: TodoItem;

  ngOnInit(): void {}
}

<div class="card">
    <div class="container">
        <h4>{{todoItem.title}} </h4>
        <span style="font-style: italic;">{{todoItem.description}} </span>
        <div>Luotu: {{todoItem.createdAt.toLocaleString()}}</div>
        <div>{{todoItem.done ? 'Tehty' : 'Kesken'}}</div>
    </div>
</div>
